server:
  port: 8081

spring:
  application:
    name: CoRSafe-poc
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: narendra
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
 
zeebe.client:
  cloud:
#    region: jfk-1
#    clusterId: c4765f54-b30c-4eba-b09f-2914741db450
#    clientId: 7JkeeCp4l93e8M.Imb1Ega0UsZg1Ylpw
#    clientSecret: SU4090ik7ZphDfrIL3pO8dyOLWpSAts2M3jN0ENC_YnA3Iatjc0YV1ZwijT6T6hj
    region: dsm-1
    clusterId: 5a77a8d1-e277-4669-9186-610ffd4ffcdd
    clientId: hPO~HhQ1TfKFCr4smfa.tl1MaiYGZCL3
    clientSecret: 7mqFCMzLTxztC.4mxvb8SvxEC-PSsjWWXejM.DVbGXSM6xTrkspnZoX~HG1IeaBv


    # WebClient properties

webclient:
  base-url: https://login.cloud.camunda.io
#razorpay:
#  key.id: rzp_test_f0aOtbLVkyCYpW
#  secret.key: CtqlYL8CjAWUOipcKFJqmSlq
